name: Android C++ Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '11'

      - name: Cache Android NDK
        id: cache-ndk
        uses: actions/cache@v4
        with:
          path: ndk/
          key: ndk-r25c-${{ runner.os }}
          restore-keys: |
            ndk-r25c-

      - name: Download Android NDK (if not cached)
        if: steps.cache-ndk.outputs.cache-hit != 'true'
        run: |
          mkdir -p ndk
          wget https://dl.google.com/android/repository/android-ndk-r25c-linux.zip
          unzip android-ndk-r25c-linux.zip -d ndk/
          echo "NDK_HOME=$GITHUB_WORKSPACE/ndk/android-ndk-r25c" >> $GITHUB_ENV

      - name: Set NDK Path
        run: echo "NDK_HOME=$GITHUB_WORKSPACE/ndk/android-ndk-r25c" >> $GITHUB_ENV

      - name: Compile C++ code
        run: |
          $NDK_HOME/ndk-build -j$(nproc) \
          NDK_PROJECT_PATH=. \
          APP_BUILD_SCRIPT=./Android.mk \
          NDK_APPLICATION_MK=./Application.mk

      - name: Upload shared libraries
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: libs
          path: libs/